### ISSUE TITLE
User level permission rules and authorisation

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Teach-Nagaland#11]
## Context: 
We have developed dashboards for Teach Nagaland team, now we have to create user level permission to access the limited count of reports as per LFE team requirement.

List of users for dashboard access and permissions provided by Client:
https://docs.google.com/spreadsheets/d/1-00fxaLq6C2OPwBQSjLul0t3ZMwRpIfh/edit#gid=1460831210

- Right now only 6 email id's have been provided by the client for state-level access of the Nagaland superset dashboard. remaining email id will be provided later.
- We previously created some user id's for app users by mistake. we need to check if some of them are overlapping between the app user and the dashboard user, The remaining users who are only is app user list are t obe voided/ deleted.
 
- [x]  check how many user id are already created from the app user list.
- [x]  create those users who have email provided in dashboard user list and not present in the app user list
- [x]  void/delete those superset users who were created by mistake from the app users list.

**Comment by vaijayanthisundaram** [comment]
Created the users on tab "APP-UAT" with appropriate permissions. Note : user id is " @teachnl ".

**Comment by salilsamanvay** [comment]
Users are to be created as per the dashboard user sheet from the file link provided in the card above.
as discussed, @vaijayanthisundaram can you please try to create users without email id, or confirm if this is not possible, will ask LFE team to provide email id for list of 25 users provided in the list.

**Comment by vaijayanthisundaram** [comment]
@salilsamanvay User creation is not possible without email id.

**Comment by BEULAHEVANJALIN** [comment]
- [x] Restrict Non-AP users from viewing NL Dashboard (7 nos)
- [x] Delete mis-created superset users
- [x] Enable Access for the following users to NL Dashboards:
     - dpd@teachnl
     - pmu1@teachnl
     - pmu2@teachnl
     - kmpg1@teachnl
     - projectmanager.lfe@teachnl
     - productmanager.lfe@teachnl 
- [x] Create admin role for the fllowing people and verify their privileges.
    - suvidhi.k@leadershipforequity.org	
    - anjaly.gopi@leadershipforequity.org	
    - anirudh.prasadh@leadershipforequity.org	 

---

NOTE: To limit access to specific charts, databases, and datasets, the following permissions have been revoked from all non-admin users in both AP and NL, assuming that they do not require access to these resources.
- menu access on Charts
- menu access on Databases
- menu access on Datasets

**Comment by Dinesh2019** [comment]
Test execution video references :

https://drive.google.com/drive/folders/13Mk98AfvAdqGqyRBvhwEq08Dl_7VD0Nv
