### ISSUE TITLE
Teach NL Superset Dashboard Documentation

### ISSUE THREAD

**Issue by adamsanadi6** [avniproject/Teach-Nagaland#12]
The goal of this documentation is to provide a thorough overview of the dashboard's functionality for both business and development users.

Link for doc file: https://docs.google.com/document/d/1XUCjyXJVmmeUNu_HO8hfVmYwaQ20KiECrlL-sPhysVs/edit#heading=h.5eudw53o5pq

- [x] Secondary Observations (Summary Dashboard) [Teach NL]
- [x] Secondary Observations (Detailed Dashboard) [NL Teach]
- [x] Classroom Observations Trackers (State Level) [NL Teach]
- [x] Classroom Observations Trackers (District Level) [NL Teach]
- [x] Operations Dashboard [Teach NL]
- [x] Primary Observations (Summary Dashboard) [Teach NL]
- [x] Primary Observations (Detailed Dashboard) [Teach NL] 
- [ ] Requirement sheet to be created for this epic by @vaijayanthisundaram for future reference

**Comment by adamsanadi6** [comment]
@Gojo-Taqi has to do Primary Observations (Summary Dashboard) [Teach NL] and Primary Observations (Detailed Dashboard) [Teach NL].
@BEULAHEVANJALIN  has to do Classroom Observations Trackers (District Level) [NL Teach].

**Comment by adamsanadi6** [comment]
@BEULAHEVANJALIN I'm done with Primary Observations (Summary Dashboard) [Teach NL] and Classroom Observations Trackers (District Level) [NL Teach].

**Comment by adamsanadi6** [comment]
@salilsamanvay Done with all 7 Dashboards.

**Comment by salilsamanvay** [comment]
@vaijayanthisundaram can you please review this document and add create a requirement sheet for Treach NL dashboard.
