### ISSUE TITLE
Budget approval required: Teach NL Dashboard change request

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Teach-Nagaland#13]
requirement document:

https://docs.google.com/spreadsheets/d/1iRYsItRdMHzQcJPJdlccuXrGAQOEL3lZD3VSSK_8kkM/edit#gid=193845630

- [x]  first we will have to analyse and estimate this requirement and then budget approval will be needed before we start work on it.

or @vinayvenu & @arjunk have a different understanding.

**Comment by vaijayanthisundaram** [comment]
Anjay has shared a modified requirements sheet. Clarifications on requirements requested from Anjaly.

**Comment by vaijayanthisundaram** [comment]
@arjunk @sachsk Please find the time estimate of the work here (current total estimate is 61.25 hrs)  (https://docs.google.com/spreadsheets/d/1PXkfDkbN3-Ht7P2xYXn4N0LHHQza-fJn7gwEhzV7o3s/edit?usp=sharing).

**Comment by vaijayanthisundaram** [comment]
Closing this and creating a new epic (Teach NL Dashboard Customization#14 ) for this as budget has been approved.
