### ISSUE TITLE
Teach NL- Primary Observations (Summary Dashboard)

### ISSUE THREAD

**Issue by vaijayanthisundaram** [avniproject/Teach-Nagaland#15]
Requirement sheet from client : https://docs.google.com/spreadsheets/d/1iRYsItRdMHzQcJPJdlccuXrGAQOEL3lZD3VSSK_8kkM/edit?usp=sharing
Pleases make the following changes :

- [x] Remove widget “District Average 4&5 Across All Elements”

- [x] Create new widget “Element Score - State Average” - For each element, this shows the avg. score at a state level. The bar graph can be represented with the x-axis as element scores from 1-5.Y-axis can be list of all 9 elements.
(Following pic in H4 in requirement sheet for reference)
     - <img width="682" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGJzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be612d709d063f64f04c0273cd0ffeb1ddf4a3bc/image.png" alt="image.png" />

- [x]  Create new widget “Element score - State average v/s District average Area wise” - The bar graph representation will be separate for each element.
For eg: for Supportive Learning Element, Y-axis will be scores 1-5  and X-axis: All 16 Districts..each district showing it's own avg element score and also representation of the state avg element score for Supportive Element Score to compare on the same bar graph.
Refer to https://drive.google.com/file/d/186nQ7JeSw40-m7bm6KyGagrnzqtfK_Rw/view?usp=sharing for sample image. 

Notes for developer :  Use element % query (Average score (4&5) across all elements)as base, but calculate avg for all scores, not just 4 &5. Change format from % to number.

- [x] Change “Average score (4&5) across all elements” to new widget name “Percentage of teachers who scored 1 to 5 for each element across the districts”. Currently, we have bar graphs representation of % teachers who scored score 4&5 across the districts.

This should be changed  for all the scores (1 to 5) for all the district. 

Notes for developer : Use "Query Quality of teaching practices primary [Teach NL]" as ref. We can do a vertical stacked bar graph by having breakdown by element.

- [x] Change from donut to bar graph for the 11 widget under the following sections :Time on Task,Classroom culture,Instruction and Socioemotional skills
- [x] Add new section name as the main title before "Classroom Culture" . New section name “Percentage of teachers who scored 1 to 5 for each element at the state level”

- [ ] The color code for each element score should be uniform through out the elements graphs. 

Preference: 1-Red, 2-Orange, 3-Blue, 4-Purple, 5- Green

Notes for developer : Colour code to be changed by changing css.

- [x] Add a Time Filter  on the dashboard to see the progression/improvement of teacher performance.
Time field to use is encountered time for encounters and for subject it is registration dttm .

**Comment by adamsanadi6** [comment]
[Click here for dashboard](http://52.66.206.164/superset/dashboard/72/)
1. Removed the chart 'District Average 4&5 Across All Elements' from the dashboard (not deleted): [link to the chart](http://52.66.206.164/superset/explore/?form_data=%7B%22viz_type%22%3A%22dist_bar%22%2C%22datasource%22%3A%22158__table%22%2C%22slice_id%22%3A945%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22created_date_time%22%2C%22time_range%22%3A%22No+filter%22%2C%22metrics%22%3A%5B%7B%22aggregate%22%3Anull%2C%22column%22%3Anull%2C%22expressionType%22%3A%22SQL%22%2C%22hasCustomLabel%22%3Atrue%2C%22isNew%22%3Afalse%2C%22label%22%3A%22Percentage%22%2C%22optionName%22%3A%22metric_v20vc11fzh_sj4nvzjky2%22%2C%22sqlExpression%22%3A%22%28%28count%28%5C%22Segment+1+-+OVERALL+POSITIVE+BEHAVIOURAL+EXPECTATIONS+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+1+-+OVERALL+POSITIVE+BEHAVIOURAL+EXPECTATIONS+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+1+-+OVERALL+LESSON+FACILITATION+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+1+-+OVERALL+LESSON+FACILITATION+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+1+-+OVERALL+CHECKS+FOR+UNDERSTANDING+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+1+-+OVERALL+CHECKS+FOR+UNDERSTANDING+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+1+-+OVERALL+FEEDBACK+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+1+-+OVERALL+FEEDBACK+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+1+-+OVERALL+CRITICAL+THINKING+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+1+-+OVERALL+CRITICAL+THINKING+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+1+-+OVERALL+SUPPORTIVE+LEARNING+ENVIRONMENT+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+1+-+OVERALL+SUPPORTIVE+LEARNING+ENVIRONMENT+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+1+-+OVERALL+AUTONOMY+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+1+-+OVERALL+AUTONOMY+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+1+-+OVERALL+PERSEVERANCE+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+1+-+OVERALL+PERSEVERANCE+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+1+-+OVERALL+SOCIAL+AND+COLLABORATIVE+SKILLS+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+1+-+OVERALL+SOCIAL+AND+COLLABORATIVE+SKILLS+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100%29+%2F+9%5Cn+++++++++++%2B%5Cn+++++++%28%28count%28%5C%22Segment+2+-+OVERALL+POSITIVE+BEHAVIOURAL+EXPECTATIONS+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+2+-+OVERALL+POSITIVE+BEHAVIOURAL+EXPECTATIONS+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+2+-+OVERALL+LESSON+FACILITATION+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+2+-+OVERALL+LESSON+FACILITATION+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+2+-+OVERALL+CHECKS+FOR+UNDERSTANDING+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+2+-+OVERALL+CHECKS+FOR+UNDERSTANDING+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+2+-+OVERALL+FEEDBACK+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+2+-+OVERALL+FEEDBACK+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+2+-+OVERALL+CRITICAL+THINKING+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+2+-+OVERALL+CRITICAL+THINKING+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+2+-+OVERALL+SUPPORTIVE+LEARNING+ENVIRONMENT+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+2+-+OVERALL+SUPPORTIVE+LEARNING+ENVIRONMENT+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+2+-+OVERALL+AUTONOMY+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+2+-+OVERALL+AUTONOMY+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+2+-+OVERALL+PERSEVERANCE+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+2+-+OVERALL+PERSEVERANCE+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100+%2B%5Cn++++++++%28count%28%5C%22Segment+2+-+OVERALL+SOCIAL+AND+COLLABORATIVE+SKILLS+SCORE%5C%22%3A%3Afloat%29%5Cn+++++++++filter+%28+where+%5C%22Segment+2+-+OVERALL+SOCIAL+AND+COLLABORATIVE+SKILLS+SCORE%5C%22%3A%3Afloat+in+%284%2C+5%29+%29%29+%2F%5Cn++++++++%28count%28%2A%29+%2A+2%29%3A%3Afloat+%2A+100%29+%2F+9%22%7D%5D%2C%22adhoc_filters%22%3A%5B%5D%2C%22groupby%22%3A%5B%22District%22%5D%2C%22columns%22%3A%5B%5D%2C%22row_limit%22%3A10000%2C%22order_desc%22%3Atrue%2C%22color_scheme%22%3A%22d3Category10%22%2C%22show_legend%22%3Atrue%2C%22show_bar_value%22%3Atrue%2C%22y_axis_format%22%3A%22SMART_NUMBER%22%2C%22y_axis_label%22%3A%22%25+Percentage+%22%2C%22show_controls%22%3Afalse%2C%22y_axis_showminmax%22%3Atrue%2C%22y_axis_bounds%22%3A%5Bnull%2Cnull%5D%2C%22x_axis_label%22%3A%22Districts%22%2C%22bottom_margin%22%3A%22auto%22%2C%22x_ticks_layout%22%3A%22auto%22%2C%22extra_form_data%22%3A%7B%7D%7D)
2. Created two new widget 
a. “Element Score - State Average” - For each element
b. "State Average Score"
3. Created a new widget: 'Element score - State average vs. District average Area wise.' This widget displays the State-Wise Average Score and District-Wise Average Score for each of the nine elements, resulting in a total of 18 charts.
4. Changed the widget name from 'Average score (4&5) across all elements' to 'Percentage of teachers who scored 1 to 5 for each element across the districts.' Additionally, modified the metric (query) to calculate the average score for all scores ranging from 1 to 5. Implemented a vertical stacked bar graph with a breakdown by element to illustrate the contribution by score (1 to 5) in percentage.
5. Changed the 'VISUALIZATION TYPE' from donut to bar graph for the 11 widgets under the following sections: Time on Task, Classroom Culture, Instruction, and Socioemotional Skills.
6. Added the new section "Percentage of teachers who scored 1 to 5 for each element at the state level" as the main title before "Classroom Culture".
7. Added a new date filter: Utilized encounterDateTime for encounters and registrationDateTime for subjects in each chart.

**Comment by adamsanadi6** [comment]
- [x] Added new charts to indicate the state average score for each element under new widget “Element score - State average v/s District average Area wise”
