### ISSUE TITLE
Teach NL Secondary Observations (Element Dashboard)

### ISSUE THREAD

**Issue by vaijayanthisundaram** [avniproject/Teach-Nagaland#17]
Requirement sheet from client : https://docs.google.com/spreadsheets/d/1iRYsItRdMHzQcJPJdlccuXrGAQOEL3lZD3VSSK_8kkM/edit?usp=sharing
Pleases make the following changes to Secondary Observations (Element Dashboard) :

- [x] Remove widget "Distribution of scores across all elements (scores 4&5) secondary". 

- [x] Add a new widget “Element Score - State Average” . For each element, show the avg. score at a state level. The bar graph can be represented with the x-axis as element scores from 1-5 and Y-axis can be list of all 9 elements.
Sample image :
<img width="681" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2JyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--addf18f560cbae410db60453228494dbd4c2b2ac/image.png" alt="image.png" />

- [x] Add a new widget “Element score - State average v/s District average Area wise” . The bar graph representation will be separate for each element wise.
For eg: for Supportive Learning Element, Y-axis will be scores 1-5  and X-axis: All 16 Districts..each district showing it's own avg element score and also representation of the state avg element score for Supportive Element Score to compare on the same bar graph. Sample image : https://drive.google.com/file/d/186nQ7JeSw40-m7bm6KyGagrnzqtfK_Rw/view?usp=sharing

Notes for developer : Use element % query (Average score (4&5) across all elements)as base, but calculate avg for all scores, not just 4 &5. Change format from % to number.

- [x] Modify “Average score (4&5) across all elements” . Change to widget name “Percentage of teachers who scored 1 to 5 for each element across the districts”.  Currently, we have bar graphs representation of % teachers who scored score 4&5 across the districts.
This should be changed to scores (1 to 5) for all the district. 
Notes for developer :  Use "Query Quality of teaching practices primary [Teach NL]" as ref. We can do a vetical stacked bar graph by having breakdown by element.

- [x] Change to bar graph For the 12 widget under the following sections : Time on Task,Classroom culture,Instruction and Socioemotional skills: 

- [x] Add new section name as the main title before "Classroom Culture" as “Percentage of teachers who scored 1 to 5 for each element at the state level”.

- [x]  The color code for each element score should be uniform through out the elements graphs. Preference: 1-Red, 2-Orange, 3-Blue, 4-Purple, 5- Green

- [x] Add a Time Filter  on the dashboard to see the progression/improvement of teacher performance.
Time field to use is encountered time for encounters and for subject it is registration dttm .

**Comment by vaijayanthisundaram** [comment]
This is the backup chart for "Distribution of scores across all elements (scores 4&5) secondary [NL Teach]-Backup" for the widget that was removed.

**Comment by adamsanadi6** [comment]
[Link to the dashboard](http://52.66.206.164/superset/dashboard/58)

**Comment by vaijayanthisundaram** [comment]
Only colour code change is remaining on this card. To pair with Sachin on this.
