### ISSUE TITLE
Teach NL - Classroom Observations Trackers (State Level)

### ISSUE THREAD

**Issue by vaijayanthisundaram** [avniproject/Teach-Nagaland#20]
Requirement sheet from client : https://docs.google.com/spreadsheets/d/1iRYsItRdMHzQcJPJdlccuXrGAQOEL3lZD3VSSK_8kkM/edit?usp=sharing
Pleases make the following changes to Classroom Observations Trackers (State Level):

- [x] Change "Completed Observations" widget name to "Observation Count". Update logic in this card to consider only observations made by observers need to be considered , and not the double coders. eg- school code like 25896625 and not like 25896625_DC

- [x] Create a new widget "Target Observation  v/s Completed Observation" as a bar graph with two bars. One showing the observation count ( do not include double coders) . The second bar shows the target which is observer count times 10.

- [x] Add a Time Filter on the dashboard to see the progression/improvement of teacher performance.
Time field to use is encountered time for encounters and for subject it is registration dttm .

**Comment by sachsk** [comment]
@vaijayanthisundaram Observation Count is less that teacher observed in this report as we are not excluding the double coded from teacher observed. check with anjaly once is it fine or not.
