### ISSUE TITLE
TeachNL Primary Dashboard Changes

### ISSUE THREAD

**Issue by Parth7223** [avniproject/Teach-Nagaland#21]
Following action items are part of primary dashboard changes:

1. Number are presented against the Y axis which is in % (Primary Observations - Behaviour Dashboard)
     - Widgets (P-31, 32) under the following sections
              Time on Task
              Classroom culture
              Instruction
              Socioemotional skills
2.  Convert to % rather than number across elements (Primary Observations - Element Dashboard)
     - Widgets (P-11, S-12) under the following sections
- [x] Time on Task
- [x] Classroom culture
- [x] Instruction
- [x] Socio-emotional skills

**Comment by adamsanadi6** [comment]
Requirement Sheet: https://docs.google.com/spreadsheets/d/1iRYsItRdMHzQcJPJdlccuXrGAQOEL3lZD3VSSK_8kkM/edit#gid=1943603797

Dashboards: 
1. [Primary Observations (Summary Dashboard) [Teach NL]](http://52.66.206.164/superset/dashboard/72)
2. [Primary Observations (Detailed Dashboard) [Teach NL]](http://52.66.206.164/superset/dashboard/73)

**Comment by adamsanadi6** [comment]
@Parth7223 , as we discussed the requirements for the first task are unclear, I'm moving this card back to the 'fresh-dev ready' lane.
