### ISSUE TITLE
TeachNL Secondary Dashboard Changes

### ISSUE THREAD

**Issue by Parth7223** [avniproject/Teach-Nagaland#22]
1. Number are presented against the Y axis which is in % (Secondary Observations - Behaviour Dashboard)
   - Widgets (P-31, 32) under the following sections
      Time on Task
      Classroom culture
       Instruction
      Socioemotional skills
2. Convert to % rather than number across elements (Secondary Observations - Element Dashboard)
    - Widgets (P-11, S-12) under the following sections
        Time on Task
        Classroom culture
         Instruction
         Socio-emotional skills
3. Remove "NULL" label from 0.1 and 0.3 Secondary observations
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--721c84eda2a6a05d147eff41a02bcfbd091499cf/Screenshot%20from%202024-02-05%2010-45-31.png" alt="Screenshot from 2024-02-05 10-45-31.png" />

**Comment by adamsanadi6** [comment]
Requirement Sheet: https://docs.google.com/spreadsheets/d/1iRYsItRdMHzQcJPJdlccuXrGAQOEL3lZD3VSSK_8kkM/edit#gid=1943603797

Dashboards:
1. [Secondary Observations (Element Dashboard) [NL Teach]](http://52.66.206.164/superset/dashboard/58)
2. [Secondary Observations (Behavior Dashboard) [NL Teach]](http://52.66.206.164/superset/dashboard/64)
