### ISSUE TITLE
TeachNL | District Wise Breakdown Required

### ISSUE THREAD

**Issue by Parth7223** [avniproject/Teach-Nagaland#23]
District wise breakdown is needed beside the existing state wise breakdown for following reports in all 32 widgets.

- [x]    - Primary Observations (Detailed Dashboard)
- [x]    - Secondary Observations (Behaviour Dashboard)

**Comment by adamsanadi6** [comment]
Dashboard Link:

1. [Primary Observations (Detailed Dashboard)](http://52.66.206.164/superset/dashboard/73)
2. [Secondary Observations (Behaviour Dashboard)](http://52.66.206.164/superset/dashboard/64)

**Comment by adamsanadi6** [comment]
@Parth7223 review the changes done in the dashboards
