### ISSUE TITLE
TeachNL | Remove 2 Widgets From Secondary Detailed Dashboard

### ISSUE THREAD

**Issue by Parth7223** [avniproject/Teach-Nagaland#24]
In the secondary observation detailed dashboard at the bottom page there are 2 widgets which are not required. These needs to be removed. 

- [x] Students are actively participating in learning tasks Agg. secondary
- [x] Supportive Learning Environment Score

**Comment by adamsanadi6** [comment]
Dashboard Link:
- [Secondary Observations (Behaviour Dashboard)](http://52.66.206.164/superset/dashboard/64)

Link to the deleted charts:

1.  [Students are actively participating in learning tasks Agg. secondary](http://52.66.206.164/superset/explore/?form_data=%7B%22viz_type%22%3A%22dist_bar%22%2C%22datasource%22%3A%22142__table%22%2C%22slice_id%22%3A828%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22encounter_date_time%22%2C%22time_range%22%3A%22No+filter%22%2C%22metrics%22%3A%5B%7B%22aggregate%22%3A%22COUNT%22%2C%22column%22%3A%7B%22certification_details%22%3Anull%2C%22certified_by%22%3Anull%2C%22column_name%22%3A%22student_participate%22%2C%22description%22%3Anull%2C%22expression%22%3Anull%2C%22filterable%22%3Atrue%2C%22groupby%22%3Atrue%2C%22id%22%3A6714%2C%22is_certified%22%3Afalse%2C%22is_dttm%22%3Afalse%2C%22python_date_format%22%3Anull%2C%22type%22%3A%22STRING%22%2C%22type_generic%22%3A1%2C%22verbose_name%22%3Anull%2C%22warning_markdown%22%3Anull%7D%2C%22expressionType%22%3A%22SIMPLE%22%2C%22hasCustomLabel%22%3Afalse%2C%22isNew%22%3Afalse%2C%22label%22%3A%22COUNT%28student_participate%29%22%2C%22optionName%22%3A%22metric_l7m107714tc_e1cc0smxjaf%22%2C%22sqlExpression%22%3Anull%7D%5D%2C%22adhoc_filters%22%3A%5B%7B%22clause%22%3A%22WHERE%22%2C%22comparator%22%3Anull%2C%22expressionType%22%3A%22SIMPLE%22%2C%22filterOptionName%22%3A%22filter_z3soxxz0q9_hdn6ntvh8rt%22%2C%22isExtra%22%3Afalse%2C%22isNew%22%3Afalse%2C%22operator%22%3A%22IS+NOT+NULL%22%2C%22operatorId%22%3A%22IS_NOT_NULL%22%2C%22sqlExpression%22%3Anull%2C%22subject%22%3A%22student_participate%22%7D%5D%2C%22groupby%22%3A%5B%22State%22%5D%2C%22columns%22%3A%5B%22student_participate%22%5D%2C%22row_limit%22%3A1000%2C%22order_desc%22%3Atrue%2C%22color_scheme%22%3A%22SUPERSET_DEFAULT%22%2C%22show_legend%22%3Atrue%2C%22show_bar_value%22%3Atrue%2C%22y_axis_format%22%3A%22~g%22%2C%22y_axis_bounds%22%3A%5Bnull%2Cnull%5D%2C%22bottom_margin%22%3A%22auto%22%2C%22x_ticks_layout%22%3A%22auto%22%2C%22extra_form_data%22%3A%7B%7D%7D)
2.  [Supportive Learning Environment Score](http://52.66.206.164/superset/explore/?form_data=%7B%22viz_type%22%3A%22dist_bar%22%2C%22datasource%22%3A%22160__table%22%2C%22slice_id%22%3A958%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22encounter_date_time%22%2C%22time_range%22%3A%22No+filter%22%2C%22metrics%22%3A%5B%7B%22aggregate%22%3Anull%2C%22column%22%3Anull%2C%22expressionType%22%3A%22SQL%22%2C%22hasCustomLabel%22%3Atrue%2C%22isNew%22%3Afalse%2C%22label%22%3A%221%22%2C%22optionName%22%3A%22metric_4503js6n0u4_i47dddfvn7%22%2C%22sqlExpression%22%3A%22%28COUNT%28%2A%29+FILTER+%28WHERE+supportive_learning+%3D+1%29%3A%3AFLOAT+%2F+COUNT%28%2A%29%3A%3AFLOAT%29%22%7D%2C%7B%22aggregate%22%3Anull%2C%22column%22%3Anull%2C%22expressionType%22%3A%22SQL%22%2C%22hasCustomLabel%22%3Atrue%2C%22isNew%22%3Afalse%2C%22label%22%3A%222%22%2C%22optionName%22%3A%22metric_rhgagwv0v8_jjjausgvwol%22%2C%22sqlExpression%22%3A%22%28COUNT%28%2A%29+FILTER+%28WHERE+supportive_learning+%3D+2%29%3A%3AFLOAT+%2F+COUNT%28%2A%29%3A%3AFLOAT%29%22%7D%2C%7B%22aggregate%22%3Anull%2C%22column%22%3Anull%2C%22expressionType%22%3A%22SQL%22%2C%22hasCustomLabel%22%3Atrue%2C%22isNew%22%3Afalse%2C%22label%22%3A%223%22%2C%22optionName%22%3A%22metric_6jsoxohsz3m_65j9o6t2qnf%22%2C%22sqlExpression%22%3A%22%28COUNT%28%2A%29+FILTER+%28WHERE+supportive_learning+%3D+3%29%3A%3AFLOAT+%2F+COUNT%28%2A%29%3A%3AFLOAT%29%22%7D%2C%7B%22aggregate%22%3Anull%2C%22column%22%3Anull%2C%22expressionType%22%3A%22SQL%22%2C%22hasCustomLabel%22%3Atrue%2C%22isNew%22%3Afalse%2C%22label%22%3A%224%22%2C%22optionName%22%3A%22metric_v18a43dkcqi_lgklk07glxi%22%2C%22sqlExpression%22%3A%22%28COUNT%28%2A%29+FILTER+%28WHERE+supportive_learning+%3D+4%29%3A%3AFLOAT+%2F+COUNT%28%2A%29%3A%3AFLOAT%29%22%7D%2C%7B%22aggregate%22%3Anull%2C%22column%22%3Anull%2C%22expressionType%22%3A%22SQL%22%2C%22hasCustomLabel%22%3Atrue%2C%22isNew%22%3Afalse%2C%22label%22%3A%225%22%2C%22optionName%22%3A%22metric_t7tnoeqq4ss_j8x38rxzvf%22%2C%22sqlExpression%22%3A%22%28COUNT%28%2A%29+FILTER+%28WHERE+supportive_learning+%3D+5%29%3A%3AFLOAT+%2F+COUNT%28%2A%29%3A%3AFLOAT%29%22%7D%5D%2C%22adhoc_filters%22%3A%5B%7B%22clause%22%3A%22WHERE%22%2C%22comparator%22%3Anull%2C%22expressionType%22%3A%22SIMPLE%22%2C%22filterOptionName%22%3A%22filter_3fih2p0agfb_8be18gaeud%22%2C%22isExtra%22%3Afalse%2C%22isNew%22%3Afalse%2C%22operator%22%3A%22IS+NOT+NULL%22%2C%22operatorId%22%3A%22IS_NOT_NULL%22%2C%22sqlExpression%22%3Anull%2C%22subject%22%3A%22supportive_learning%22%7D%5D%2C%22groupby%22%3A%5B%22State%22%5D%2C%22columns%22%3A%5B%5D%2C%22row_limit%22%3A1000%2C%22order_desc%22%3Atrue%2C%22contribution%22%3Afalse%2C%22color_scheme%22%3A%22SUPERSET_DEFAULT%22%2C%22show_legend%22%3Atrue%2C%22show_bar_value%22%3Atrue%2C%22order_bars%22%3Afalse%2C%22y_axis_format%22%3A%22.2%25%22%2C%22y_axis_label%22%3A%22Percentage+%28%25%29%22%2C%22y_axis_showminmax%22%3Atrue%2C%22y_axis_bounds%22%3A%5B0%2C1%5D%2C%22x_axis_label%22%3A%22Score%22%2C%22bottom_margin%22%3A%22auto%22%2C%22x_ticks_layout%22%3A%22auto%22%2C%22extra_form_data%22%3A%7B%7D%7D)
