### ISSUE TITLE
TeachNL | Classroom Observations | Changes

### ISSUE THREAD

**Issue by Parth7223** [avniproject/Teach-Nagaland#26]
- [x] Add Observer name and school code column is in the Inactive users table (Classroom Observations Trackers (State Level))

**Comment by adamsanadi6** [comment]
Dashboard Link:
1. [Classroom Observations Trackers (District Level) [NL Teach]](http://52.66.206.164/superset/dashboard/71)
2. [Classroom Observations Trackers (State Level) [NL Teach]](http://52.66.206.164/superset/dashboard/70)
