### ISSUE TITLE
Secondary Observations (Summary Dashboard) [Teach Nagaland]

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Teach-Nagaland#3]
Please refer epic for context and details:

AP dashboard link which is to be referred to create this dashboard for Nagaland
http://52.66.206.164/superset/dashboard/28/?native_filters=%28%29

Changes agreed to implement on this card:
1. The location filter is to be changed from Mandal to Block, as Nagaland has blocks instead of Mandal.
2. Bolcks observed and school-observed indicators as shown in the classroom observation state-level dashboard should be added here as well.
3. One more filter level needs to be added to select a school 

Additional checks/ issues that are observed in AP dashboard are to be cross-checked on this dashboard as well:
1	Count where blocks are too many and figures are overlapping each other have to be explored if that can be presented diagonally or in any other way by which it doesn't overlap
2	in AP dashboard for some reports filter of district level is not filtering blocks related to that district only, need to check this point while creating for NL

**Comment by adamsanadi6** [comment]
Currently working on  #7

**Comment by salilsamanvay** [comment]
@adamsanadi6 as a process please add a comment on the card about what you have done, in this case, it would have been better to add the link of the dashboard that you have created so far.

**Comment by adamsanadi6** [comment]
Link for Summary dashboard: http://52.66.206.164/superset/dashboard/58/
Apart from filter chart everything is done.

**Comment by vaijayanthisundaram** [comment]
@adamsanadi6 Link is for AP dashboard, please provide correct one.

**Comment by adamsanadi6** [comment]
@vaijayanthisundaram Updated the link

**Comment by adamsanadi6** [comment]
@vaijayanthisundaram Updated the link
