### ISSUE TITLE
Secondary Observations (Detailed Dashboard) [Teach Nagaland]

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Teach-Nagaland#4]

**Comment by adamsanadi6** [comment]
Link: http://52.66.206.164/superset/dashboard/64/

**Comment by vaijayanthisundaram** [comment]
0.1 Teacher provides a learning activity to most students - NULL needs to be removed
0.3 Students are actively participating in learning tasks - NULL needs to be removed

**Comment by adamsanadi6** [comment]
Did the changes in 0.1 and 0.3 charts.
