### ISSUE TITLE
Primary Observations (Summary Dashboard) [Teach Nagaland]

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Teach-Nagaland#5]

**Comment by Gojo-Taqi** [comment]
Link to the dashboard - http://52.66.206.164/superset/dashboard/65/?native_filters=%28NATIVE_FILTER-3i8V2Avix%3A%28extraFormData%3A%28%29%2CfilterState%3A%28%29%2Cid%3ANATIVE_FILTER-3i8V2Avix%2CownState%3A%28%29%29%2CNATIVE_FILTER-Kklp3QrEC%3A%28extraFormData%3A%28%29%2CfilterState%3A%28%29%2Cid%3ANATIVE_FILTER-Kklp3QrEC%2CownState%3A%28%29%29%2CNATIVE_FILTER-Nsgja_b-1%3A%28extraFormData%3A%28%29%2CfilterState%3A%28%29%2Cid%3ANATIVE_FILTER-Nsgja_b-1%2CownState%3A%28%29%29%29

**Comment by vaijayanthisundaram** [comment]
- Change metric name in chart display for “District Average 4&5 Across All Elements” for easier understanding.

**Comment by adamsanadi6** [comment]
Changed the metric name
