### ISSUE TITLE
Primary Observations (Detailed Dashboard) [Teach Nagaland]

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Teach-Nagaland#6]

**Comment by salilsamanvay** [comment]
@BEULAHEVANJALIN @Gojo-Taqi who is working on this card?

**Comment by BEULAHEVANJALIN** [comment]
http://52.66.206.164/superset/dashboard/66/?native_filters=%28NATIVE_FILTER-0pXGeVx8C%3A%28extraFormData%3A%28%29%2CfilterState%3A%28%29%2Cid%3ANATIVE_FILTER-0pXGeVx8C%2CownState%3A%28%29%29%2CNATIVE_FILTER-jyV9WR_q8%3A%28extraFormData%3A%28%29%2CfilterState%3A%28%29%2Cid%3ANATIVE_FILTER-jyV9WR_q8%2CownState%3A%28%29%29%2CNATIVE_FILTER-sGIpmbLZL%3A%28extraFormData%3A%28%29%2CfilterState%3A%28%29%2Cid%3ANATIVE_FILTER-sGIpmbLZL%2CownState%3A%28%29%29%29

**Comment by vaijayanthisundaram** [comment]
Distribution of scores across all elements (scores 4&5) mandal wise - change metric name 
1. SUPPORTIVE LEARNING ENIVRONMENT -change metric name
0.1 Teacher provides a learning activity to most students - remove NULL
0.2 Students are on task - remove NULL
1.4.a The teacher does not exhibit bias (Gender) and challenges stereotypes in the classroom - remove NULL

**Comment by adamsanadi6** [comment]
Made the above changes.
Also changed the name of the chart from Distribution of scores across all elements (scores 4&5) mandal wise to Distribution of scores across all elements (scores 4&5) black wise
