### ISSUE TITLE
Classroom Observations Trackers (State Level) [Teach Nagaland]

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Teach-Nagaland#7]

**Comment by adamsanadi6** [comment]
Link: http://52.66.206.164/superset/dashboard/61/?native_filters=%28%29

**Comment by adamsanadi6** [comment]
Fixed the count mismatch with Teachers Observed and Total Teachers Registered Vs Observed

**Comment by adamsanadi6** [comment]
Fixed the count mismatch with Teachers Observed and Total Teachers Registered Vs Observed

**Comment by salilsamanvay** [comment]
heat map is getting crashed once the user tries to click on the map

**Comment by Gojo-Taqi** [comment]
@salilsamanvay I don't think this fix is possible.
@sachsk can we fix this? is there a way?

**Comment by vaijayanthisundaram** [comment]
Userwise Observation not Done Count-  looks like multiple entries for each user. Group by need not include "District", "Block", "School" if we are not displaying it.

**Comment by adamsanadi6** [comment]
Some users are assigned to conduct observations in various "District", "Block", and "School". Consequently, there are multiple entries for certain users.

Also for chart filtering, we require information on the "District", "Block" and "School".
