### ISSUE TITLE
Classroom Observations Trackers (District Level) [Teach Nagaland]

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Teach-Nagaland#8]

**Comment by salilsamanvay** [comment]
@BEULAHEVANJALIN link of the dashboard is not updated on this card

**Comment by salilsamanvay** [comment]
the map is crashing once the user tries to select anything on the map chart

**Comment by vaijayanthisundaram** [comment]
Metric name on charts need to be updated.

**Comment by adamsanadi6** [comment]
The metric names on charts have been updated.
